# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'
gem 'rspec', '~> 3.13'

gem 'rake', '~> 13.3'

group :development do
  gem 'pry'
  gem 'rubocop'
end

gem 'liquid', '~> 5.11'
